apiVersion: projectcalico.org/v3
kind: GlobalAlert
metadata:
  name: waf.protect-cve-2021-44228-log4j-exploitation-attempt
spec:
  description: "Generate alerts for CVE-2021-44228 Log4j exploitation attempt ruleset matches"
  summary: "Generate alerts for CVE-2021-44228 Log4j exploitation attempt ruleset matches"
  severity: 100
  dataSet: waf
  period: 1m
  lookback: 1m
  query: '"rule_info" IN {"*1005*"}'
  aggregateBy: [rule_info, method, path, destination.hostname, destination.ip, source.hostname, source.ip]
---
apiVersion: projectcalico.org/v3
kind: GlobalAlert
metadata:
  name: waf-new-alert-rule-info
spec:
  summary: 'WAF new waf-alert-942100'
  description: 'Test WAF Global Alert'
  severity: 1
  dataSet: waf
  period: 1m
  lookback: 1m
  query: '"rule_info" IN {"*942100*"}'
  threshold: 0
  condition: gt
